### ISSUE TITLE
Don't create tag with undefined values

### ISSUE THREAD

**Issue by hbatalhaStch** [divijhardwaj/json-xml-parse#4]
I am running into issues where I have objects with properties that can be `undefined` and in cases where they are undefined I don't want tags being created for them

**Comment by dlvlj** [comment]
Hi, thanks for reporting the issue.

I tried input below
`const test = {
  name: {
    "#" : {
      tag1: "tag1-name",
      tag2: {
        "#" : {
          tag3: undefined
        }
      }
    }
  }
}
`
output
```xml
<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<name>
	<tag1>tag1-name</tag1>
	<tag2>
		<tag3>undefined</tag3>
	</tag2>
</name>
```
I can see it is creating tags but the content is set as undefined. I am working on adding a type handler in the next version. Can you please provide a small sample input for which the package fails to create tags, also provide the expected output.

Thank you

**Comment by hbatalhaStch** [comment]
Thank you for the fast reply.
Sorry, I missed one word in my post, I edited it.
I don't want tags for undefined properties being created.

[The code ](https://github.com/dlvlj/json-xml-parse/blob/cdfe78a3d66811598fb5ff23dd274eeafdb73c6c/src/js-xml/js-to-xml.ts#L68) could be something like this:
```ts
Object.keys(data).forEach((key) => {
        if (!!data[key])
          generateXmlString(key, data[key], 0);
      })
```

Or maybe add a configuration to control such behaviour.

**Comment by dlvlj** [comment]
No problem, I see now what the problem is.
Thanks for providing the code snippet, that helps.

I like your idea for a configuration-based method,
based on this I am currently implementing a type-handling option for the package,
using which devs can determine what values to show inside the tag or not show the tag at all.

I will try to release the new version in a day or two and will let you know about it.

**Comment by hbatalhaStch** [comment]
> I will try to release the new version in a day or two and will let you know about it.

Thank you. Looking forward to it.

**Comment by dlvlj** [comment]
Hi, I have pushed the changes on the branch "v2".
The readme is updated with function parameters order change and type handler addition.

I want to give some time to test it before I release it meanwhile, you can build and try using it if you want.
Let me know if you have any suggestions or encounter any issues.

type handler for undefined
```js
const typeHandler = (val) => [!!val, val]
```

Thanks

**Comment by hbatalhaStch** [comment]
Great way to handle this use case. 
But I believe `typeHandler` should be put inside the `options` object since at the end of the day it is still a type of configuration. It is no different from `contentKey`, `attrKey` or `beautify`. Also it would be make the `toXmlString` function cleaner.

Also about `toXmlString` function, I would make the `props` parameter ([this line](https://github.com/dlvlj/json-xml-parse/blob/312a32315e6928879ab3ac8d9d1c0d4862b854d0/src/js-xml/js-to-xml.ts#L8)) nullable since all its props are nullable, so that I can avoid having to be doing this:
```ts
// passing an empty options object because typescript will complain if I don't
const xml  = jsXml.toXmlString(jsonData,{})parameter
```
It would be better if I can just do this:
```ts
const xml  = jsXml.toXmlString(jsonData)
```

They both accomplish the same thing.

**Comment by hbatalhaStch** [comment]
https://github.com/dlvlj/json-xml-parse/commit/312a32315e6928879ab3ac8d9d1c0d4862b854d0#r141152878

**Comment by dlvlj** [comment]
@hbatalhaStch you are right about including the `typeHandler` inside of the options, I have made that change, and the nullable `props` should also be working fine now, I also refactored the logic and finally got time to push the changes. I will do some testing before publishing it.

I really appreciate your help in making this package better.

**Comment by hbatalhaStch** [comment]
> @hbatalhaStch you are right about including the `typeHandler` inside of the options, I have made that change, and the nullable `props` should also be working fine now, I also refactored the logic and finally got time to push the changes. I will do some testing before publishing it.

Great, please let me know when you publish it.

> I really appreciate your help in making this package better.

Glad to know and thank you for such a great package.

**Comment by dlvlj** [comment]
@hbatalhaStch Hi, v1.3.0 is finally been published, apologies for the delayed release.
Thank you very much for contributing. Feel free to create a pull request.
